1..10
# Started on 03/22/16 21:58:32
# Starting class: TestAnotherThing
ok     1	TestAnotherThing.test1_Success1
ok     2	TestAnotherThing.test1_Success2
not ok 3	TestAnotherThing.test3_Fail1
#   test/test_with_err_fail_pass.lua:49: expected: 0, actual: 2
#   stack traceback:
#   	test/test_with_err_fail_pass.lua:49: in function 'TestAnotherThing.test3_Fail1'
not ok 4	TestAnotherThing.test3_Fail2
#   test/test_with_err_fail_pass.lua:53: expected: 0, actual: 3
#   stack traceback:
#   	test/test_with_err_fail_pass.lua:53: in function 'TestAnotherThing.test3_Fail2'
# Starting class: TestSomething
ok     5	TestSomething.test1_Success1
ok     6	TestSomething.test1_Success2
not ok 7	TestSomething.test2_Fail1
#   test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
#   stack traceback:
#   	test/test_with_err_fail_pass.lua:15: in function 'TestSomething.test2_Fail1'
not ok 8	TestSomething.test2_Fail2
#   test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
#   stack traceback:
#   	test/test_with_err_fail_pass.lua:19: in function 'TestSomething.test2_Fail2'
not ok 9	testFuncFail1
#   test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
#   stack traceback:
#   	test/test_with_err_fail_pass.lua:62: in function 'testFuncFail1'
ok     10	testFuncSuccess1
# Ran 10 tests in 0.000 seconds, 5 successes, 5 failures, 5 non-selected
