<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
    <testsuite name="LuaUnit" id="00001" package="" hostname="localhost" tests="15" timestamp="2016-03-22T21:29:18" time="0.003" errors="5" failures="5">
        <properties>
            <property name="Lua Version" value="Lua 5.1"/>
            <property name="LuaUnit Version" value="3.3"/>
        </properties>
        <testcase classname="TestAnotherThing" name="TestAnotherThing.test1_Success1" time="0.000">
        </testcase>
        <testcase classname="TestAnotherThing" name="TestAnotherThing.test1_Success2" time="0.000">
        </testcase>
        <testcase classname="TestAnotherThing" name="TestAnotherThing.test2_Err1" time="0.000">
            <error type="test/test_with_err_fail_pass.lua:41: attempt to perform arithmetic on a table value">
                <![CDATA[stack traceback:
	[C]: in function 'xpcall']]></error>
        </testcase>
        <testcase classname="TestAnotherThing" name="TestAnotherThing.test2_Err2" time="0.000">
            <error type="test/test_with_err_fail_pass.lua:45: attempt to perform arithmetic on a table value">
                <![CDATA[stack traceback:
	[C]: in function 'xpcall']]></error>
        </testcase>
        <testcase classname="TestAnotherThing" name="TestAnotherThing.test3_Fail1" time="0.000">
            <failure type="test/test_with_err_fail_pass.lua:49: expected: 0, actual: 2">
                <![CDATA[stack traceback:
	test/test_with_err_fail_pass.lua:49: in function 'TestAnotherThing.test3_Fail1']]></failure>
        </testcase>
        <testcase classname="TestAnotherThing" name="TestAnotherThing.test3_Fail2" time="0.000">
            <failure type="test/test_with_err_fail_pass.lua:53: expected: 0, actual: 3">
                <![CDATA[stack traceback:
	test/test_with_err_fail_pass.lua:53: in function 'TestAnotherThing.test3_Fail2']]></failure>
        </testcase>
        <testcase classname="TestSomething" name="TestSomething.test1_Success1" time="0.000">
        </testcase>
        <testcase classname="TestSomething" name="TestSomething.test1_Success2" time="0.000">
        </testcase>
        <testcase classname="TestSomething" name="TestSomething.test2_Fail1" time="0.000">
            <failure type="test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2">
                <![CDATA[stack traceback:
	test/test_with_err_fail_pass.lua:15: in function 'TestSomething.test2_Fail1']]></failure>
        </testcase>
        <testcase classname="TestSomething" name="TestSomething.test2_Fail2" time="0.000">
            <failure type="test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3">
                <![CDATA[stack traceback:
	test/test_with_err_fail_pass.lua:19: in function 'TestSomething.test2_Fail2']]></failure>
        </testcase>
        <testcase classname="TestSomething" name="TestSomething.test3_Err1" time="0.000">
            <error type="test/test_with_err_fail_pass.lua:23: attempt to perform arithmetic on a table value">
                <![CDATA[stack traceback:
	[C]: in function 'xpcall']]></error>
        </testcase>
        <testcase classname="TestSomething" name="TestSomething.test3_Err2" time="0.000">
            <error type="test/test_with_err_fail_pass.lua:27: attempt to perform arithmetic on a table value">
                <![CDATA[stack traceback:
	[C]: in function 'xpcall']]></error>
        </testcase>
        <testcase classname="[TestFunctions]" name="testFuncErr1" time="0.000">
            <error type="test/test_with_err_fail_pass.lua:66: attempt to perform arithmetic on a table value">
                <![CDATA[stack traceback:
	[C]: in function 'xpcall']]></error>
        </testcase>
        <testcase classname="[TestFunctions]" name="testFuncFail1" time="0.000">
            <failure type="test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3">
                <![CDATA[stack traceback:
	test/test_with_err_fail_pass.lua:62: in function 'testFuncFail1']]></failure>
        </testcase>
        <testcase classname="[TestFunctions]" name="testFuncSuccess1" time="0.000">
        </testcase>
    <system-out/>
    <system-err/>
    </testsuite>
</testsuites>
